# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220f0852470bd039c9e2e4f9a61bbb35f8b09ad32eb9ec35cdd5a90497f3c6318e9a8ddd4352492576f4042ec195fb9533590bda5010d39a42c1a86e7e7bda1e

test:
  secret_key_base: 973ce9a171d94d1bf2a0db5e3ae7896e0d6a4997c91050e22ebaeb43289535186d97e7493091c8058dd3fccb8e7eb2d6d8287200b17604ac6908929f62a34ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
